//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibraryStandard.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClassLibraryStandard.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;PreviousPlatforms xsi:schemaLocation=&quot;http://microsoft.com/schemas/Windows/SDK/PreviousPlatforms ./PreviousPlatformsXmlSchema.xsd&quot; xmlns=&quot;http://microsoft.com/schemas/Windows/SDK/PreviousPlatforms&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///	&lt;ApplicationPlatform name=&quot;DesktopPlatform&quot; friendlyName=&quot;Windows Desktop Extension SDK&quot; version=&quot;10.0.22000.0&quot;&gt;
        ///		&lt;DependentPlatform name=&quot;UAP&quot; version=&quot;10.0.22000.0&quot;/&gt;
        ///		&lt;VersionedContent&gt;true&lt;/VersionedContent&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DesktopPreviousPlatforms {
            get {
                return ResourceManager.GetString("DesktopPreviousPlatforms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;PreviousPlatforms xmlns=&quot;http://microsoft.com/schemas/Windows/SDK/PreviousPlatforms&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xsi:schemaLocation=&quot;http://microsoft.com/schemas/Windows/SDK/PreviousPlatforms ./PreviousPlatformsXmlSchema.xsd&quot;&gt;
        ///  &lt;ApplicationPlatform name=&quot;IoTPlatform&quot; friendlyName=&quot;Windows IoT Extension SDK&quot; version=&quot;10.0.17134.0&quot;&gt;
        ///    &lt;DependentPlatform name=&quot;UAP&quot; version=&quot;10.0.17134.0&quot;/&gt;
        ///    &lt;VersionedContent&gt;true&lt;/VersionedContent&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IoTPreviousPlatforms {
            get {
                return ResourceManager.GetString("IoTPreviousPlatforms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;PreviousPlatforms xsi:schemaLocation=&quot;http://microsoft.com/schemas/Windows/SDK/PreviousPlatforms ./PreviousPlatformsXmlSchema.xsd&quot; xmlns=&quot;http://microsoft.com/schemas/Windows/SDK/PreviousPlatforms&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///  &lt;ApplicationPlatform name=&quot;MobilePlatform&quot; friendlyName=&quot;Windows Mobile Extension SDK&quot; version=&quot;10.0.22000.0&quot;&gt;
        ///    &lt;DependentPlatform name=&quot;UAP&quot; version=&quot;10.0.22000.0&quot;/&gt;
        ///    &lt;VersionedContent&gt;true&lt;/VersionedConte [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MobilePreviousPlatforms {
            get {
                return ResourceManager.GetString("MobilePreviousPlatforms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:Windows.ApplicationModel:CameraApplicationManager
        ///Method:Windows.ApplicationModel:CameraApplicationManager:ShowInstalledApplicationsUI:Void:()
        ///Type:Windows.ApplicationModel:DesignMode
        ///Property:Windows.ApplicationModel:DesignMode:DesignModeEnabled:Boolean:{get;}
        ///Type:Windows.ApplicationModel:ISuspendingDeferral
        ///Method:Windows.ApplicationModel:ISuspendingDeferral:Complete:Void:()
        ///Type:Windows.ApplicationModel:ISuspendingEventArgs
        ///Property:Windows.ApplicationModel:ISuspendingEventArgs:SuspendingOpe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PhoneBlue {
            get {
                return ResourceManager.GetString("PhoneBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;PreviousPlatforms xsi:schemaLocation=&quot;http://microsoft.com/schemas/Windows/SDK/PreviousPlatforms ./PreviousPlatformsXmlSchema.xsd&quot; xmlns=&quot;http://microsoft.com/schemas/Windows/SDK/PreviousPlatforms&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///  &lt;ApplicationPlatform name=&quot;PPIPlatform&quot; friendlyName=&quot;Windows Team Extension SDK&quot; version=&quot;10.0.22000.0&quot;&gt;
        ///    &lt;DependentPlatform name=&quot;UAP&quot; version=&quot;10.0.22000.0&quot;/&gt;
        ///    &lt;VersionedContent&gt;true&lt;/VersionedContent&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TeamPreviousPlatforms {
            get {
                return ResourceManager.GetString("TeamPreviousPlatforms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;PreviousPlatforms xsi:schemaLocation=&quot;http://microsoft.com/schemas/Windows/SDK/PreviousPlatforms ./PreviousPlatformsXmlSchema.xsd&quot; xmlns=&quot;http://microsoft.com/schemas/Windows/SDK/PreviousPlatforms&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///
        ///  &lt;ApplicationPlatform name=&quot;UAP&quot; friendlyName=&quot;Windows 11&quot; version=&quot;10.0.22000.0&quot;&gt;
        ///    &lt;VersionedContent&gt;true&lt;/VersionedContent&gt;
        ///    &lt;ContainedApiContracts&gt;
        ///      &lt;ApiContract name=&quot;Windows.AI.MachineLearning.M [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UapPreviousPlatforms {
            get {
                return ResourceManager.GetString("UapPreviousPlatforms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:Windows.ApplicationModel:DesignMode
        ///Property:Windows.ApplicationModel:DesignMode:DesignModeEnabled:Boolean:{get;}
        ///Type:Windows.ApplicationModel:ISuspendingDeferral
        ///Method:Windows.ApplicationModel:ISuspendingDeferral:Complete:Void:()
        ///Type:Windows.ApplicationModel:ISuspendingEventArgs
        ///Property:Windows.ApplicationModel:ISuspendingEventArgs:SuspendingOperation:SuspendingOperation:{get;}
        ///Type:Windows.ApplicationModel:ISuspendingOperation
        ///Property:Windows.ApplicationModel:ISuspendingOperation:Deadline [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Win8 {
            get {
                return ResourceManager.GetString("Win8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:Windows.ApplicationModel:DesignMode
        ///Property:Windows.ApplicationModel:DesignMode:DesignModeEnabled:Boolean:{get;}
        ///Type:Windows.ApplicationModel:ISuspendingDeferral
        ///Method:Windows.ApplicationModel:ISuspendingDeferral:Complete:Void:()
        ///Type:Windows.ApplicationModel:ISuspendingEventArgs
        ///Property:Windows.ApplicationModel:ISuspendingEventArgs:SuspendingOperation:SuspendingOperation:{get;}
        ///Type:Windows.ApplicationModel:ISuspendingOperation
        ///Property:Windows.ApplicationModel:ISuspendingOperation:Deadline [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WinBlue {
            get {
                return ResourceManager.GetString("WinBlue", resourceCulture);
            }
        }
    }
}
